# Generated by Django 5.0.7 on 2024-07-14 03:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplyJob',
            new_name='ApplyJobModel',
        ),
    ]
