# Generated by Django 5.0.7 on 2024-07-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_rename_applyjob_applyjobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Graphic Design', 'Graphic Design'), ('IT and Programming', 'IT and Programming'), ('Marketing', 'Marketing'), ('Sales and Management', 'Sales and Management')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
