# Generated by Django 5.0.7 on 2024-07-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_jobmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Graphic Design', 'Graphic Design'), ('IT and Programming', 'IT and Programming'), ('Marketing', 'Marketing'), ('Sales and Management', 'Sales and Management')], default='Education', max_length=30),
        ),
    ]
